/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { BaseConstants } from './BaseConstants'

export class AppStorageKeyConstants {
  public static readonly KEY_WIDTH_BREAKPOINT: string = BaseConstants.KEY_PREFIX + 'WidthBreakPoint';
  public static readonly KEY_HEIGHT_BREAKPOINT: string = BaseConstants.KEY_PREFIX + 'HeightBreakPoint';
  public static readonly KEY_WINDOW_UTIL: string = BaseConstants.KEY_PREFIX + 'WindowUtil'
  public static readonly KEY_IS_PLAY: string = BaseConstants.KEY_PREFIX + 'IsPlay'
  public static readonly KEY_CURRENT_TIME: string = BaseConstants.KEY_PREFIX + 'CurrentTime'
  public static readonly KEY_TOTAL_TIME: string = BaseConstants.KEY_PREFIX + 'TotalTime'
  public static readonly KEY_TOTAL_MS_TIME: string = BaseConstants.KEY_PREFIX + 'TotalMsTime'
  public static readonly KEY_PROGRESS_MAX: string = BaseConstants.KEY_PREFIX + 'ProgressMax'
  public static readonly KEY_PROGRESS: string = BaseConstants.KEY_PREFIX + 'Progress'
  public static readonly KEY_IMAGE_COLOR: string = BaseConstants.KEY_PREFIX + 'ImageColor'
  public static readonly KEY_PAGE_SHOW_TIME: string = BaseConstants.KEY_PREFIX + 'PageShowTime'
  public static readonly KEY_SONG_LIST: string = BaseConstants.KEY_PREFIX + 'SongList'
  public static readonly KEY_LIBRARY_REVISION: string = BaseConstants.KEY_PREFIX + 'LibraryRevision'
  public static readonly KEY_FILTER_REVISION: string = BaseConstants.KEY_PREFIX + 'FilterRevision'
  public static readonly KEY_PLAY_MODE: string = BaseConstants.KEY_PREFIX + 'PlayMode'
  public static readonly KEY_SELECT_INDEX: string = BaseConstants.KEY_PREFIX + 'SelectIndex'
  public static readonly KEY_CURRENT_SPEED: string = BaseConstants.KEY_PREFIX + 'CurrentSpeed'
  public static readonly KEY_CURRENT_VOLUME: string = BaseConstants.KEY_PREFIX + 'CurrentVolume'
  public static readonly KEY_IS_FAVORITE: string = BaseConstants.KEY_PREFIX + 'IsFavorite'
  public static readonly KEY_TOP_HEIGHT: string = BaseConstants.KEY_PREFIX + 'TopHeight'
  public static readonly KEY_BOTTOM_HEIGHT: string = BaseConstants.KEY_PREFIX + 'BottomHeight'
  public static readonly KEY_TITLE_BUTTON_WIDTH: string = BaseConstants.KEY_PREFIX + 'TitleButtonWidth'
  public static readonly KEY_TITLE_BUTTON_HEIGHT: string = BaseConstants.KEY_PREFIX + 'TitleButtonHeight'
  public static readonly KEY_UI_ABILITY_CONTEXT: string = BaseConstants.KEY_PREFIX + 'UIAbilityContext'
  public static readonly KEY_WINDOW: string = BaseConstants.KEY_PREFIX + 'Window'
}
