import { SongItem } from './SongData'

export const songList: SongItem[] = [
  {
    id: 1,
    title: '歌曲一',
    singer: '歌手一',
    cover: $r('app.media.ic_public_music'),
    src: '',
    index: 0
  },
  {
    id: 2,
    title: '歌曲二',
    singer: '歌手二',
    cover: $r('app.media.ic_public_music'),
    src: '',
    index: 1
  },
  {
    id: 3,
    title: '歌曲三',
    singer: '歌手三',
    cover: $r('app.media.ic_public_music'),
    src: '',
    index: 2
  }
]
